"""Prompt assembly, the refusal sentinel, and decline copy.

Declines are generated by the server, never by the model — that is what makes
them consistent, testable, and identical between the eval harness and the UI
(ARCHITECTURE.md §7).
"""
from __future__ import annotations

from dataclasses import dataclass

SENTINEL = "INSUFFICIENT_CONTEXT"

# Copy differs from the local build, which invites the reader to upload a
# document. There is nothing to upload here: the corpus is fixed and ingested
# offline (PRD §4, non-goals). Offering a remedy the reader cannot take makes a
# deliberate refusal read as a broken one, which is exactly what PRD G5 asks
# this path to avoid.
DECLINE_COPY = {
    "empty_corpus": (
        "The document index is empty, so there is nothing to search. This is a "
        "deployment fault rather than a limit of your question — the corpus is "
        "meant to be ingested before the service accepts traffic."
    ),
    "off_domain": (
        "I can only answer questions grounded in the drug labels that make up "
        "this corpus, and this question isn't covered by them."
    ),
    "weak_unsupported": (
        "I found some possibly related material, but not close enough to answer "
        "this reliably. Try rephrasing it in the label's own terms."
    ),
    "insufficient_context": (
        "This corpus covers the topic, but doesn't contain enough detail to "
        "answer this specific question. I'd rather decline than guess."
    ),
}

FALLBACK_DECLINE = "I can't answer that from the documents in this corpus."

SYSTEM_TEMPLATE = """You are a clinical reference assistant for a fixed corpus of drug labels.

Answer only using the context below, drawn from that corpus.
Do not draw on general knowledge beyond what is in the context.

If the context does not contain enough information to answer the question, your
entire response must be the exact characters {sentinel} — nothing before it,
nothing after it, no greeting, no explanation, no punctuation.

When you do answer, cite the numbered sources you used, like [1] or [2].
Your answers are for informational reference only and are not a substitute for
professional medical judgment.

Context:
{context}"""


@dataclass(frozen=True)
class ContextChunk:
    chunk_id: str
    title: str
    page_number: int
    text: str


def decline_text(reason: str) -> str:
    return DECLINE_COPY.get(reason, FALLBACK_DECLINE)


def format_context(chunks: list[ContextChunk]) -> str:
    return "\n\n".join(
        f"[{i}] ({c.title}, p. {c.page_number})\n{c.text}"
        for i, c in enumerate(chunks, start=1)
    )


def _trim_history(history: list[dict], max_history: int, history_chars: int) -> list[dict]:
    """Keep the most recent turns that fit the character budget.

    Skips an oversized message rather than stopping, so one long turn (a pasted
    lab report) does not also discard smaller, older turns that would have fit.
    Then drops any leading assistant turn: an assistant message with no user
    message before it is malformed conversation and gives the model a reply to
    a question it cannot see.

    The hosted profile is single-turn and always passes an empty history (PRD
    §4, non-goals). This is kept, unchanged and tested, because multi-turn is
    deferred rather than rejected — and because keeping it means this module
    stays diffable against the local build, which is what makes divergence
    between the two visible.
    """
    recent = history[-max_history:] if max_history else []
    kept: list[dict] = []
    budget = history_chars
    for message in reversed(recent):
        cost = len(message["content"])
        if cost > budget:
            continue
        budget -= cost
        kept.append(message)
    kept.reverse()
    while kept and kept[0]["role"] == "assistant":
        kept.pop(0)
    return kept


def build_messages(
    question: str,
    chunks: list[ContextChunk],
    history: list[dict],
    max_history: int = 4,
    history_chars: int = 2000,
) -> list[dict]:
    if not chunks:
        # Answering with no retrieved context is the failure this whole system
        # exists to prevent. Callers must decline via the gate instead.
        raise ValueError("build_messages requires at least one context chunk")
    system = SYSTEM_TEMPLATE.format(sentinel=SENTINEL, context=format_context(chunks))
    return [
        {"role": "system", "content": system},
        *_trim_history(history, max_history, history_chars),
        {"role": "user", "content": question},
    ]
